FROM alpine/git as facefusion-docker
WORKDIR /facefusion-docker
RUN git clone https://github.com/facefusion/facefusion-docker.git .

FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/facefusion/facefusion.git .
COPY --from=facefusion-docker /facefusion-docker/requirements-docker.cuda.txt .
RUN pip install -r requirements-docker.cuda.txt
