FROM python:3.10

ARG FACEFUSION_VERSION=1.0.0

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/facefusion/facefusion.git --branch $FACEFUSION_VERSION .
RUN curl -o requirements-docker.cpu.txt https://raw.githubusercontent.com/facefusion/facefusion-docker/master/requirements-docker.cpu.txt
RUN pip install -r requirements-docker.cpu.txt
