FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ARG FACEFUSION_VERSION=1.2.0
ENV GRADIO_SERVER_NAME=0.0.0.0

WORKDIR /facefusion

RUN apt-get update && \
	apt-get install -y \
	python3.10 python-is-python3 pip git ffmpeg curl && \
	rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 https://github.com/facefusion/facefusion.git --branch $FACEFUSION_VERSION --single-branch .
RUN python install.py --onnxruntime cuda
